server:
  port: 9000
  tomcat:
    max-connections: 10000 # 최대 10,000개의 동시 연결 처리 가능
    accept-count: 1000 # 최대 1,000개의 대기 요청 처리 가능
    threads:
      max: 1000 # 최대 1,000개의 요청 처리 스레드 사용
      min-spare: 1000 # 최소 1,000개의 대기 스레드 유지

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/fastsns
    username: root
    password: fastcampus123@
  data:
    redis:
      host: localhost
      port: 6379