spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: "jdbc:mysql://localhost:3307/fastsns"
    username: root
    password: fastcampus123@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    show-sql: true